# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d64710c07cbad6db4ac6ce125bc2a6d91bc8672cd1b712a732d5e2d822edf05b00b21471cbd89e3322f66362d24d75ce7b8636ad697a74967c6692040b3d752

test:
  secret_key_base: ced6dc6d5219075cc4298519ed961d9fa11169ee299a1b93b16fbf3e369c07f6d41e221673c1fd77539b2208d23478d7e942560334e215375f4f14eb4a8c9ae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
